server:
  port: 64278 #${PORT:0}

spring:
  application:
    name: library-api
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/library}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 1800000
      idle-timeout: 600000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    name: application.log
  level:
    root: warn
    io:
      github:
        cursodsousa: info # trace
    org:
      springFramework:
        # web: debug
      web: info

management:
  server:
    port: 0
  endpoints:
    web:
      exposure:
        include: "*"

# Perfil de Produção
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false

# Perfil de Homologação
---
spring:
  config:
    activate:
      on-profile: homologacao
  jpa:
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/library